# Generated by Django 5.2.8 on 2025-11-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Le nom de la catégorie doit être renseigné.', 'max_length': 'Le nom de la catégorie ne peut excéder 150 caractères.', 'unique': 'Une catégorie ayant le même nom existe déjà.'}, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(error_messages={'blank': 'Le description de la tâche doit être complétée.', 'max_length': 'La description ne doit pas dépasser 2000 caractères.'}, max_length=2000)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
        ),
    ]
