# Generated by Django 5.2.8 on 2025-11-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'blank': 'Le nom de la catégorie doit être renseigné.', 'max_length': 'Le nom de la catégorie ne peut excéder 100 caractères.', 'unique': 'Une catégorie ayant le même nom existe déjà.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(error_messages={'invalid': 'Catégorie inexistante.'}, on_delete=django.db.models.deletion.CASCADE, to='tasks.category'),
        ),
    ]
