# Generated by Django 5.2.8 on 2025-11-20 13:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_category_name_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'blank': 'Le nom de la catégorie doit être renseigné.', 'max_length': 'Le nom de la catégorie ne peut excéder 100 caractères.'}, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name_ci', violation_error_message='Une catégorie ayant le même nom existe déjà.'),
        ),
    ]
